### ISSUE TITLE
Error for PHP version 8.0.3

### ISSUE THREAD

**Issue by jack-silva** [bogdanghervan/revolut-statement#1]
Hi @bogdanghervan, thank you for putting together this app!

I've got the latest version of PHP but when I ran revolut-statement I got the following error:
 
![image](https://user-images.githubusercontent.com/63585976/110956959-15663780-8343-11eb-93f2-8b1d0c8298bb.png)

**Comment by bogdanghervan** [comment]
Hi @jack-silva, I fixed this in the latest version. Could you download the latest build and try again?

Here's how to download it into your `/usr/local/bin` folder if you've been following the docs:
```
php -r "copy('https://github.com/bogdanghervan/revolut-statement/raw/main/builds/revolut-statement', '/usr/local/bin/revolut-statement');" && chmod u+x /usr/local/bin/revolut-statement
```
